# Generated by Django 4.2 on 2024-06-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdfriendrequests',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_received_requests', to='apis.socialprofile'),
        ),
        migrations.AlterField(
            model_name='acceptdfriendrequests',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_sent_requests', to='apis.socialprofile'),
        ),
        migrations.AlterField(
            model_name='pendingfriendrequests',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_received_requests', to='apis.socialprofile'),
        ),
        migrations.AlterField(
            model_name='pendingfriendrequests',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_sent_requests', to='apis.socialprofile'),
        ),
        migrations.AlterField(
            model_name='rejectedfriendrequests',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_received_requests', to='apis.socialprofile'),
        ),
        migrations.AlterField(
            model_name='rejectedfriendrequests',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_sent_requests', to='apis.socialprofile'),
        ),
    ]
